# USAGE: GOOGLE_CLIENT_ID='...' docker-compose --project-name google-login up

version: '3'

services:
  app:
    build: '.'
    environment:
      PORT: 8080
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
    ports:
      - '8080:8080'
